import type { Metadata } from "next";
import "./styles/globals.css";
import Body from "./components/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Body>
        {children}
      </Body>
    </html>
  );
}
